; PlatformIO Project Configuration
; Docs: https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Optional: uncomment and set your local serial port
; upload_port = /dev/ttyUSB0
; monitor_port = /dev/ttyUSB0

; Add libs as needed, examples:
; lib_deps =
;   bblanchon/ArduinoJson @ ^7.0.0

build_flags =
  -DCORE_DEBUG_LEVEL=1
